pull_request_rules:
  - name: automatically merge my (eikek) PRs on CI success
    conditions:
      - author=eikek
      - base=master
      - status-success=ci
    actions:
      merge:
        method: merge
